language: python
python:
- '3.6'
services: postgresql
env:
  global:
    - DEBUG=True
    - SECRET_KEY=s3cr3tk3y
    secure: "j5ww6sxzQeLpKfNqn2Sv3g6cXGm5YQbsZ4cmS6FXeKo3ZAbM1G1+a2g5KUVh2gOPhucS9cAD6E9WexweB0qH5je9kuRDcWzNBQ/4TPUOSJz2GzgKc7mpngwdaXGLTQBR46hOa6/0xZtLgKN/7W11AQ2jP6+cDmGY4UVWOEuxiO6vScVQAB4KfR+ge+RmoGknzSSOec5cllY4HV6Z1wGKvJNYe5RA88HcuNHNg9wFvbsQQW8MvjwgjRaCAwrVDxyhmWcnrn/Z5ZAZYoPbc91CAxAdY4MGRXKQEy8f4qxkqhUIGLP4npIPJa2S5+fT9nrZvBX7SjkaXm2l9bIjGfoy0Oe8HdhJqZDwe6Dl5DttZfNgQUbuPzTc0998ZuSr12Levyi2tsrRT6htwyZgiXSq/wxcncx90zImcN4pb3dgLG8AwFnzLDUvqK1JMlra/Zzn/ALf5Weojmlb3jBgVmVKxOKzTjEmXGjNwEYsluOmECsi3MVnXoLOTZbD3aerK1f4/8Mu24vQBAGQfzK2YcIyWg6IY8Cpim8w5HLfipzn3w73xW5YZsbhAZnA7+5MRtn+IeGGwn8m8JAxWJTPsrEbgt8WaXt19mUMVgsuVQHxDMAdXfvm929f8HF4TN3quI7oKv+p6r2yqrOensF5iSSu/hZFu8A++ycXbopPOubohyc="
  matrix:
    - DJANGO_VERSION="1.11"
    - DJANGO_VERSION="2.1.5"
install:
- pip install -q Django==$DJANGO_VERSION
- pip install coverage
- pip install flake8
- pip install coveralls
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
- python manage.py --version
- python manage.py makemigrations auth core profiles projects courses
- python manage.py migrate
script:
- flake8 --select=T003
- coverage run --source='.' manage.py test
after_success:
- coveralls
