# Travis build configuration

# Originally adapted from:
#   https://docs.travis-ci.com/user/languages/python/#Examples

language: python
python:
  # - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  - "3.6"
  # - "3.6-dev" # 3.6 development branch
  # - "3.7-dev" # 3.7 development branch
  # - "nightly" # currently points to 3.7-dev


services: postgresql

# Set global env variables for settings.py
# Set matrix env variables to run multiple builds with
# different configurations.
env:
  global:
    # Note that DATABASE_URL is not set here, see settings.py
    - DEBUG=True
    - SECRET_KEY=s3cr3tk3y
  # Test against multiple Django versions
  # https://docs.travis-ci.com/user/languages/ ...
  #   python/#Testing-Against-Multiple-Versions-of-Dependencies-(e.g.-Django-or-Flask)
  matrix:
    - DJANGO_VERSION="1.10.5"
    - DJANGO_VERSION="1.11"


# Install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

# Create a test database
before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python manage.py makemigrations auth core profiles projects courses
  - python manage.py migrate

# Run tests
script: 
  - python manage.py test