# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190213_1510'),
        ('profiles', '0003_auto_20190207_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='known_techs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='learn_techs',
        ),
        migrations.DeleteModel(
            name='Techs',
        ),
    ]
