# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190213_1510'),
        ('profiles', '0003_auto_20190220_0255'),
        ('profiles', '0003_auto_20190221_0016'),
    ]

    operations = [
    ]
