# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190308_0100'),
        ('profiles', '0004_auto_20190311_0820'),
        ('profiles', '0005_merge_20190224_2018'),
    ]

    operations = [
    ]
