# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190118_0352'),
        ('projects', '0007_auto_20190213_1510'),
    ]

    operations = [
    ]
