# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-15 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_project_desired_techs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default='', max_length=2000)),
                ('duration', models.FloatField(default='1')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Project Plan',
                'ordering': ('-date',),
            },
        ),
    ]
