# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_merge_20190224_2018'),
        ('projects', '0008_merge_20190224_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Techs',
        ),
        migrations.AddField(
            model_name='project',
            name='desired_techs',
            field=models.ManyToManyField(default='', related_name='technologies', to='profiles.Techs'),
        ),
    ]
