# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-26 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_remove_projectplan_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectplan',
            unique_together=set([('project', 'create_user')]),
        ),
    ]
