# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190224_2036'),
        ('projects', '0010_auto_20190526_1408'),
    ]

    operations = [
    ]
