# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190308_0100'),
        ('courses', '0009_course_receivers'),
    ]

    operations = [
    ]
